package com.ikenna.portfolios.infos;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "DocInfo")
public class Doc {
    @DynamoDBHashKey(attributeName = "docId")
    @DynamoDBAutoGeneratedKey
        private String docId;
    @DynamoDBAttribute
        private String docName;
    @DynamoDBAttribute
        private String docType;
    @DynamoDBAttribute
        private String urlDownload;

}
