package com.ikenna.portfolios.infos;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "EducationInfo")
public class Education{

    @DynamoDBHashKey(attributeName = "eduId")
    @DynamoDBAutoGeneratedKey
    private String eduId;
    @DynamoDBAttribute
    private String schoolName;
    @DynamoDBAttribute
    private String major;
    @DynamoDBAttribute
    private String concentration;
    @DynamoDBAttribute
    private String honor;
    @DynamoDBAttribute
    private String city;
    @DynamoDBAttribute
    private String state;
    @DynamoDBAttribute
    private String country;
    @DynamoDBAttribute
    private String educationImage;
    @DynamoDBAttribute
    private String startDate;
    @DynamoDBAttribute
    private String endDate;
}
