package com.ikenna.portfolios.infos;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "PersonalInfo")
public class Info {
    @DynamoDBHashKey(attributeName = "infoId")
    @DynamoDBAutoGeneratedKey
    private String infoId;
    @DynamoDBAttribute
    private String firstName;
    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String occupation;
    @DynamoDBAttribute
    private String personalImage;
    @DynamoDBAttribute
    private String fileName;
    @DynamoDBAttribute
    private String phone;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String summary;
}
