package com.ikenna.portfolios.infos;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ProjectInfo")
public class Project {
    @DynamoDBHashKey(attributeName = "projectId")
    @DynamoDBAutoGeneratedKey
    private String projectId;
    @DynamoDBAttribute
    private String projectTitle;
    @DynamoDBAttribute
    private String keyRole;
    @DynamoDBAttribute
    private String projectSummary;
    @DynamoDBAttribute
    private String projectImage;
    @DynamoDBAttribute
    private String progress;
    @DynamoDBAttribute
    private String projectLink;
    @DynamoDBAttribute
    private int progressRate;
    @DynamoDBAttribute
    private String startDate;
    @DynamoDBAttribute
    private String endDate;


}
