package com.ikenna.portfolios.infos;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
@DynamoDBDocument
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "WorkInfo")
public class Work {
    @DynamoDBHashKey(attributeName = "workId")
    @DynamoDBAutoGeneratedKey
    private String workId;
    //one to many with info
    @DynamoDBAttribute
    private String companyName;
    @DynamoDBAttribute
    private String jobTitle;
    @DynamoDBAttribute
    private String jobDescription;
    @DynamoDBAttribute
    private Date startDate;
    @DynamoDBAttribute
    private Date endDate;
    @DynamoDBAttribute
    private String workImage;
    @DynamoDBAttribute
    private String city;
    @DynamoDBAttribute
    private String state;
    @DynamoDBAttribute
    private String country;
}
